### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mathijs159**
Whoops, wrong branch

### CODE REVIEW

**Comment by peterthorpe5** [comment]
HI mathijs159,

I am very pleased to see someone getting involved with my code. Thanks. Just so you know this top BLAST based method applied in this script is fragile to database error (database error meaning sequences in NCBI not being what they actually are! I have examples if you wish). The output of the script will return many candidates. The Check_contamination_on_contigs.py script help prioritise and reduce the number of candidates. 

Are you using this script for you own research. I will review the changes you have made and the merge them into the main branch... thanks again for your input!

cheers,

Pete

**Comment by mathijs159** [comment]
Thanks for taking it lightly, I would greatly appreciate if you could supply a few examples.
I'm mostly adapting the script to work with a slightly different blast format and organism. Nothing major planned.

Mathijs

**Comment by peterthorpe5** [comment]
There is test data in the folder to try it on. Let me know how you get on with this.
The code should be already set up to work for different organisms. Just change the options. The BLAST format is standard tab plus kingdom assignments. 

parser.add_option("--tax_filter_out", dest="tax_filter_out", default="6656",
                  help="The tax ID to filter out: for this analysis the Phylum which your BEAST"
                  "of interest if found. e.g. Aphids are from Arthropoda, therefore this would be "
                  "6656, whihc is the dwefault value. This will filter out all blast hit which are "
                  "from this phylum. It is possible to put a species/kingdom tax_id in here ... what"
                  "ever floats your boat.")

parser.add_option("--tax_filter_up_to", dest="tax_filter_up_to", default="33208",
                  help=" The tax_id to 'walk up to', to determine assignment. By default this is metazoa."
                  "The script work out the best metazoan to non-metazoan hit. But this can be altered if "
"you wish to alter this")

 As for example of database error: If you run this on aphid C002 and Me10 sequences, then they come through as HGT events having been acquired from a human pathogen Clostridium sordellii strain ATCC 9714 . However, these aphid sequences hit no other C. sodelli strain or bacteria species. Human pathogen and aphid do not share the same ecological niche. Therefore I do not believe this. So, just be careful ….

**Comment by mathijs159** [comment]
Thanks for the heads up, rest assured, my conclusions won't be automated. :)

**Pull request closed without merging**
